audit_header: false
title: Wilmington's Best Real Estate Training
description: Aimee Freeman, a top Real Estate Agent in Wilmington, shares her own internal real estate agent training for free. Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: About
    url: /about/
  - title: 
    url: #
  - title: 
    url: 
  - title: 
    url: 


client:
  name: Aimee Freeman
  title:
  license_number:
  about_markdown: |
    I was born in Pennsylvania & moved to North Carolina over 30 years ago with my family. I have been in the real estate industry since 1998 & have worked many different aspects of the business. I have two grown children & two cuddly fur babies. In my free time, I enjoy relaxing at the beach, traveling & watching Sunday football.

    Real estate is my passion! I am hooked on masterminding with agents across the country that are doing real estate bigger, better & faster than we are. After all, you are the sum of the five people that you spend the most time with, right? As a result, I am extremely blessed to be in THREE elite coaching groups across the country. I am also a national real estate coach for one of them. My extensive & ongoing training, coaching & mentorship will not only help our team to grow, but it will also allow us to serve our clients better.
    
  market: Wilmington
  brand: Aimee & Co.
  brokerage: Keller Williams Realty
  address: 1001 Military Cutoff Road Suite 101<br>Wilmington, NC 28405
  phone: 704-965-8333
  phone_type:
  phone2:
  phone2_type:
  email: aimee@aimeeandco.com
  url: http://www.aimeeandco.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: "Looking to take your business to new heights?"
    CTA_text: "Let's talk about how Aimee & Co. can help."
    CTA_link_text: "Schedule a Consultation"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a Wilmington Home?"
#     CTA_text2: "Search the entire MLS for your Wilmington home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Wilmington Real Estate Podcast with Aimee Freeman'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Wilmington Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Aimee & Co. - your professional Wilmington Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Wilmington, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Aimee Freeman'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Wilmington Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b63e3e'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
